package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CambioRevision generated by hbm2java
 */
@Entity
@Table(name = "cambio_revision", catalog = "car2")
public class CambioRevision implements java.io.Serializable {

	private Integer idCambioRevision;
	private MantencionBase mantencionBaseByIdCambio;
	private MantencionBase mantencionBaseByIdRevision;
	private Date fechaModificacion;

	public CambioRevision() {
	}

	public CambioRevision(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public CambioRevision(MantencionBase mantencionBaseByIdCambio, MantencionBase mantencionBaseByIdRevision,
			Date fechaModificacion) {
		this.mantencionBaseByIdCambio = mantencionBaseByIdCambio;
		this.mantencionBaseByIdRevision = mantencionBaseByIdRevision;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cambio_revision", unique = true, nullable = false)
	public Integer getIdCambioRevision() {
		return this.idCambioRevision;
	}

	public void setIdCambioRevision(Integer idCambioRevision) {
		this.idCambioRevision = idCambioRevision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cambio")
	public MantencionBase getMantencionBaseByIdCambio() {
		return this.mantencionBaseByIdCambio;
	}

	public void setMantencionBaseByIdCambio(MantencionBase mantencionBaseByIdCambio) {
		this.mantencionBaseByIdCambio = mantencionBaseByIdCambio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_revision")
	public MantencionBase getMantencionBaseByIdRevision() {
		return this.mantencionBaseByIdRevision;
	}

	public void setMantencionBaseByIdRevision(MantencionBase mantencionBaseByIdRevision) {
		this.mantencionBaseByIdRevision = mantencionBaseByIdRevision;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
