package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampaniaUsuario generated by hbm2java
 */
@Entity
@Table(name = "campania_usuario", catalog = "car2")
public class CampaniaUsuario implements java.io.Serializable {

	private Long idCampaniaUsuario;
	private Campania campania;
	private Usuario usuario;
	private Date fechaSincro;
	private Date fechaModificacion;

	public CampaniaUsuario() {
	}

	public CampaniaUsuario(Campania campania, Usuario usuario, Date fechaModificacion) {
		this.campania = campania;
		this.usuario = usuario;
		this.fechaModificacion = fechaModificacion;
	}

	public CampaniaUsuario(Campania campania, Usuario usuario, Date fechaSincro, Date fechaModificacion) {
		this.campania = campania;
		this.usuario = usuario;
		this.fechaSincro = fechaSincro;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_campania_usuario", unique = true, nullable = false)
	public Long getIdCampaniaUsuario() {
		return this.idCampaniaUsuario;
	}

	public void setIdCampaniaUsuario(Long idCampaniaUsuario) {
		this.idCampaniaUsuario = idCampaniaUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_campania", nullable = false)
	public Campania getCampania() {
		return this.campania;
	}

	public void setCampania(Campania campania) {
		this.campania = campania;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_sincro", length = 19)
	public Date getFechaSincro() {
		return this.fechaSincro;
	}

	public void setFechaSincro(Date fechaSincro) {
		this.fechaSincro = fechaSincro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
