package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CiaSeguros generated by hbm2java
 */
@Entity
@Table(name = "cia_seguros", catalog = "car2")
public class CiaSeguros implements java.io.Serializable {

	private Integer idCiaSeguros;
	private String nombre;
	private String datosAnexos;
	private Date fechaModificacion;
	private Set<SeguroVehiculo> seguroVehiculos = new HashSet<SeguroVehiculo>(0);

	public CiaSeguros() {
	}

	public CiaSeguros(String nombre, Date fechaModificacion) {
		this.nombre = nombre;
		this.fechaModificacion = fechaModificacion;
	}

	public CiaSeguros(String nombre, String datosAnexos, Date fechaModificacion, Set<SeguroVehiculo> seguroVehiculos) {
		this.nombre = nombre;
		this.datosAnexos = datosAnexos;
		this.fechaModificacion = fechaModificacion;
		this.seguroVehiculos = seguroVehiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cia_seguros", unique = true, nullable = false)
	public Integer getIdCiaSeguros() {
		return this.idCiaSeguros;
	}

	public void setIdCiaSeguros(Integer idCiaSeguros) {
		this.idCiaSeguros = idCiaSeguros;
	}

	@Column(name = "nombre", nullable = false, length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "datos_anexos", length = 65535)
	public String getDatosAnexos() {
		return this.datosAnexos;
	}

	public void setDatosAnexos(String datosAnexos) {
		this.datosAnexos = datosAnexos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciaSeguros")
	public Set<SeguroVehiculo> getSeguroVehiculos() {
		return this.seguroVehiculos;
	}

	public void setSeguroVehiculos(Set<SeguroVehiculo> seguroVehiculos) {
		this.seguroVehiculos = seguroVehiculos;
	}

}
