package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Combustible generated by hbm2java
 */
@Entity
@Table(name = "combustible", catalog = "car2")
public class Combustible implements java.io.Serializable {

	private byte idCombustible;
	private String descripcion;
	private Date fechaModificacion;
	private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

	public Combustible() {
	}

	public Combustible(byte idCombustible, String descripcion, Date fechaModificacion) {
		this.idCombustible = idCombustible;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
	}

	public Combustible(byte idCombustible, String descripcion, Date fechaModificacion, Set<Vehiculo> vehiculos) {
		this.idCombustible = idCombustible;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.vehiculos = vehiculos;
	}

	@Id

	@Column(name = "id_combustible", unique = true, nullable = false)
	public byte getIdCombustible() {
		return this.idCombustible;
	}

	public void setIdCombustible(byte idCombustible) {
		this.idCombustible = idCombustible;
	}

	@Column(name = "descripcion", nullable = false, length = 16)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "combustible")
	public Set<Vehiculo> getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set<Vehiculo> vehiculos) {
		this.vehiculos = vehiculos;
	}

}
