package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contingencia generated by hbm2java
 */
@Entity
@Table(name = "contingencia", catalog = "car2")
public class Contingencia implements java.io.Serializable {

	private Long idContingencia;
	private Date fechaInicio;
	private Date fechaFin;
	private String detalleHtml;
	private String regiones;
	private Date fechaModificacion;

	public Contingencia() {
	}

	public Contingencia(Date fechaInicio, Date fechaFin, String detalleHtml, String regiones, Date fechaModificacion) {
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.detalleHtml = detalleHtml;
		this.regiones = regiones;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_contingencia", unique = true, nullable = false)
	public Long getIdContingencia() {
		return this.idContingencia;
	}

	public void setIdContingencia(Long idContingencia) {
		this.idContingencia = idContingencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", nullable = false, length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", nullable = false, length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "detalle_html", nullable = false, length = 65535)
	public String getDetalleHtml() {
		return this.detalleHtml;
	}

	public void setDetalleHtml(String detalleHtml) {
		this.detalleHtml = detalleHtml;
	}

	@Column(name = "regiones", nullable = false, length = 64)
	public String getRegiones() {
		return this.regiones;
	}

	public void setRegiones(String regiones) {
		this.regiones = regiones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
