package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MantencionUsuario generated by hbm2java
 */
@Entity
@Table(name = "mantencion_usuario", catalog = "car2")
public class MantencionUsuario implements java.io.Serializable {

	private MantencionUsuarioId id;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private String beneficios;
	private String url;
	private Boolean dependeKm;
	private Integer kmEntreMantenciones;
	private Integer mesesEntreMantenciones;
	private Date fechaModificacion;
	private boolean borrado;
	private Set<MantencionUsuarioHecha> mantencionUsuarioHechas = new HashSet<MantencionUsuarioHecha>(0);

	public MantencionUsuario() {
	}

	public MantencionUsuario(MantencionUsuarioId id, Usuario usuario, Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.usuario = usuario;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	public MantencionUsuario(MantencionUsuarioId id, Usuario usuario, String nombre, String descripcion,
			String beneficios, String url, Boolean dependeKm, Integer kmEntreMantenciones,
			Integer mesesEntreMantenciones, Date fechaModificacion, boolean borrado,
			Set<MantencionUsuarioHecha> mantencionUsuarioHechas) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.beneficios = beneficios;
		this.url = url;
		this.dependeKm = dependeKm;
		this.kmEntreMantenciones = kmEntreMantenciones;
		this.mesesEntreMantenciones = mesesEntreMantenciones;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
		this.mantencionUsuarioHechas = mantencionUsuarioHechas;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMantencionUsuario", column = @Column(name = "id_mantencion_usuario", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)) })
	public MantencionUsuarioId getId() {
		return this.id;
	}

	public void setId(MantencionUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 1024)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "beneficios", length = 65535)
	public String getBeneficios() {
		return this.beneficios;
	}

	public void setBeneficios(String beneficios) {
		this.beneficios = beneficios;
	}

	@Column(name = "url", length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "depende_km")
	public Boolean getDependeKm() {
		return this.dependeKm;
	}

	public void setDependeKm(Boolean dependeKm) {
		this.dependeKm = dependeKm;
	}

	@Column(name = "km_entre_mantenciones")
	public Integer getKmEntreMantenciones() {
		return this.kmEntreMantenciones;
	}

	public void setKmEntreMantenciones(Integer kmEntreMantenciones) {
		this.kmEntreMantenciones = kmEntreMantenciones;
	}

	@Column(name = "meses_entre_mantenciones")
	public Integer getMesesEntreMantenciones() {
		return this.mesesEntreMantenciones;
	}

	public void setMesesEntreMantenciones(Integer mesesEntreMantenciones) {
		this.mesesEntreMantenciones = mesesEntreMantenciones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "borrado", nullable = false)
	public boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionUsuario")
	public Set<MantencionUsuarioHecha> getMantencionUsuarioHechas() {
		return this.mantencionUsuarioHechas;
	}

	public void setMantencionUsuarioHechas(Set<MantencionUsuarioHecha> mantencionUsuarioHechas) {
		this.mantencionUsuarioHechas = mantencionUsuarioHechas;
	}

}
