package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MantencionBaseHechaId generated by hbm2java
 */
@Embeddable
public class MantencionBaseHechaId implements java.io.Serializable {

	private int idMantencionBaseHecha;
	private long idUsuario;

	public MantencionBaseHechaId() {
	}

	public MantencionBaseHechaId(int idMantencionBaseHecha, long idUsuario) {
		this.idMantencionBaseHecha = idMantencionBaseHecha;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_mantencion_base_hecha", nullable = false)
	public int getIdMantencionBaseHecha() {
		return this.idMantencionBaseHecha;
	}

	public void setIdMantencionBaseHecha(int idMantencionBaseHecha) {
		this.idMantencionBaseHecha = idMantencionBaseHecha;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MantencionBaseHechaId))
			return false;
		MantencionBaseHechaId castOther = (MantencionBaseHechaId) other;

		return (this.getIdMantencionBaseHecha() == castOther.getIdMantencionBaseHecha())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMantencionBaseHecha();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
