package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MantencionBase generated by hbm2java
 */
@Entity
@Table(name = "mantencion_base", catalog = "car2")
public class MantencionBase implements java.io.Serializable {

	private Long idMantencionBase;
	private String nombre;
	private String traccion;
	private String combustible;
	private String accion;
	private String beneficios;
	private String descripcionItem;
	private String url;
	private Boolean dependeKm;
	private Integer kmEntreMantenciones;
	private Integer mesesEntreMantenciones;
	private Date fechaModificacion;
	private Set<MantencionPospuesta> mantencionPospuestas = new HashSet<MantencionPospuesta>(0);
	private Set<CambioRevision> cambioRevisionsForIdCambio = new HashSet<CambioRevision>(0);
	private Set<CambioRevision> cambioRevisionsForIdRevision = new HashSet<CambioRevision>(0);
	private Set<Alerta> alertas = new HashSet<Alerta>(0);
	private Set<ConsultaProveedor> consultaProveedors = new HashSet<ConsultaProveedor>(0);
	private Set<MantencionBaseHecha> mantencionBaseHechas = new HashSet<MantencionBaseHecha>(0);
	private Set<ProveedorMantencionBase> proveedorMantencionBases = new HashSet<ProveedorMantencionBase>(0);

	public MantencionBase() {
	}

	public MantencionBase(String nombre, String traccion, String combustible, Date fechaModificacion) {
		this.nombre = nombre;
		this.traccion = traccion;
		this.combustible = combustible;
		this.fechaModificacion = fechaModificacion;
	}

	public MantencionBase(String nombre, String traccion, String combustible, String accion, String beneficios,
			String descripcionItem, String url, Boolean dependeKm, Integer kmEntreMantenciones,
			Integer mesesEntreMantenciones, Date fechaModificacion, Set<MantencionPospuesta> mantencionPospuestas,
			Set<CambioRevision> cambioRevisionsForIdCambio, Set<CambioRevision> cambioRevisionsForIdRevision,
			Set<Alerta> alertas, Set<ConsultaProveedor> consultaProveedors,
			Set<MantencionBaseHecha> mantencionBaseHechas, Set<ProveedorMantencionBase> proveedorMantencionBases) {
		this.nombre = nombre;
		this.traccion = traccion;
		this.combustible = combustible;
		this.accion = accion;
		this.beneficios = beneficios;
		this.descripcionItem = descripcionItem;
		this.url = url;
		this.dependeKm = dependeKm;
		this.kmEntreMantenciones = kmEntreMantenciones;
		this.mesesEntreMantenciones = mesesEntreMantenciones;
		this.fechaModificacion = fechaModificacion;
		this.mantencionPospuestas = mantencionPospuestas;
		this.cambioRevisionsForIdCambio = cambioRevisionsForIdCambio;
		this.cambioRevisionsForIdRevision = cambioRevisionsForIdRevision;
		this.alertas = alertas;
		this.consultaProveedors = consultaProveedors;
		this.mantencionBaseHechas = mantencionBaseHechas;
		this.proveedorMantencionBases = proveedorMantencionBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_mantencion_base", unique = true, nullable = false)
	public Long getIdMantencionBase() {
		return this.idMantencionBase;
	}

	public void setIdMantencionBase(Long idMantencionBase) {
		this.idMantencionBase = idMantencionBase;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "traccion", nullable = false, length = 3)
	public String getTraccion() {
		return this.traccion;
	}

	public void setTraccion(String traccion) {
		this.traccion = traccion;
	}

	@Column(name = "combustible", nullable = false, length = 16)
	public String getCombustible() {
		return this.combustible;
	}

	public void setCombustible(String combustible) {
		this.combustible = combustible;
	}

	@Column(name = "accion", length = 64)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "beneficios", length = 65535)
	public String getBeneficios() {
		return this.beneficios;
	}

	public void setBeneficios(String beneficios) {
		this.beneficios = beneficios;
	}

	@Column(name = "descripcion_item", length = 65535)
	public String getDescripcionItem() {
		return this.descripcionItem;
	}

	public void setDescripcionItem(String descripcionItem) {
		this.descripcionItem = descripcionItem;
	}

	@Column(name = "url", length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "depende_km")
	public Boolean getDependeKm() {
		return this.dependeKm;
	}

	public void setDependeKm(Boolean dependeKm) {
		this.dependeKm = dependeKm;
	}

	@Column(name = "km_entre_mantenciones")
	public Integer getKmEntreMantenciones() {
		return this.kmEntreMantenciones;
	}

	public void setKmEntreMantenciones(Integer kmEntreMantenciones) {
		this.kmEntreMantenciones = kmEntreMantenciones;
	}

	@Column(name = "meses_entre_mantenciones")
	public Integer getMesesEntreMantenciones() {
		return this.mesesEntreMantenciones;
	}

	public void setMesesEntreMantenciones(Integer mesesEntreMantenciones) {
		this.mesesEntreMantenciones = mesesEntreMantenciones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBase")
	public Set<MantencionPospuesta> getMantencionPospuestas() {
		return this.mantencionPospuestas;
	}

	public void setMantencionPospuestas(Set<MantencionPospuesta> mantencionPospuestas) {
		this.mantencionPospuestas = mantencionPospuestas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBaseByIdCambio")
	public Set<CambioRevision> getCambioRevisionsForIdCambio() {
		return this.cambioRevisionsForIdCambio;
	}

	public void setCambioRevisionsForIdCambio(Set<CambioRevision> cambioRevisionsForIdCambio) {
		this.cambioRevisionsForIdCambio = cambioRevisionsForIdCambio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBaseByIdRevision")
	public Set<CambioRevision> getCambioRevisionsForIdRevision() {
		return this.cambioRevisionsForIdRevision;
	}

	public void setCambioRevisionsForIdRevision(Set<CambioRevision> cambioRevisionsForIdRevision) {
		this.cambioRevisionsForIdRevision = cambioRevisionsForIdRevision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBase")
	public Set<Alerta> getAlertas() {
		return this.alertas;
	}

	public void setAlertas(Set<Alerta> alertas) {
		this.alertas = alertas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBase")
	public Set<ConsultaProveedor> getConsultaProveedors() {
		return this.consultaProveedors;
	}

	public void setConsultaProveedors(Set<ConsultaProveedor> consultaProveedors) {
		this.consultaProveedors = consultaProveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBase")
	public Set<MantencionBaseHecha> getMantencionBaseHechas() {
		return this.mantencionBaseHechas;
	}

	public void setMantencionBaseHechas(Set<MantencionBaseHecha> mantencionBaseHechas) {
		this.mantencionBaseHechas = mantencionBaseHechas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantencionBase")
	public Set<ProveedorMantencionBase> getProveedorMantencionBases() {
		return this.proveedorMantencionBases;
	}

	public void setProveedorMantencionBases(Set<ProveedorMantencionBase> proveedorMantencionBases) {
		this.proveedorMantencionBases = proveedorMantencionBases;
	}

}
