package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MantencionPospuestaId generated by hbm2java
 */
@Embeddable
public class MantencionPospuestaId implements java.io.Serializable {

	private int idMantencionPospuesta;
	private long idUsuario;

	public MantencionPospuestaId() {
	}

	public MantencionPospuestaId(int idMantencionPospuesta, long idUsuario) {
		this.idMantencionPospuesta = idMantencionPospuesta;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_mantencion_pospuesta", nullable = false)
	public int getIdMantencionPospuesta() {
		return this.idMantencionPospuesta;
	}

	public void setIdMantencionPospuesta(int idMantencionPospuesta) {
		this.idMantencionPospuesta = idMantencionPospuesta;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MantencionPospuestaId))
			return false;
		MantencionPospuestaId castOther = (MantencionPospuestaId) other;

		return (this.getIdMantencionPospuesta() == castOther.getIdMantencionPospuesta())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMantencionPospuesta();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
