package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MantencionUsuarioHechaId generated by hbm2java
 */
@Embeddable
public class MantencionUsuarioHechaId implements java.io.Serializable {

	private long idMantencionUsuarioHecha;
	private long idUsuario;

	public MantencionUsuarioHechaId() {
	}

	public MantencionUsuarioHechaId(long idMantencionUsuarioHecha, long idUsuario) {
		this.idMantencionUsuarioHecha = idMantencionUsuarioHecha;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_mantencion_usuario_hecha", nullable = false)
	public long getIdMantencionUsuarioHecha() {
		return this.idMantencionUsuarioHecha;
	}

	public void setIdMantencionUsuarioHecha(long idMantencionUsuarioHecha) {
		this.idMantencionUsuarioHecha = idMantencionUsuarioHecha;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MantencionUsuarioHechaId))
			return false;
		MantencionUsuarioHechaId castOther = (MantencionUsuarioHechaId) other;

		return (this.getIdMantencionUsuarioHecha() == castOther.getIdMantencionUsuarioHecha())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdMantencionUsuarioHecha();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
