package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "car2")
public class Marca implements java.io.Serializable {

	private short idMarca;
	private Pais pais;
	private TipoVehiculo tipoVehiculo;
	private String descripcion;
	private Date fechaModificacion;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);

	public Marca() {
	}

	public Marca(short idMarca, Pais pais, TipoVehiculo tipoVehiculo, String descripcion, Date fechaModificacion) {
		this.idMarca = idMarca;
		this.pais = pais;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
	}

	public Marca(short idMarca, Pais pais, TipoVehiculo tipoVehiculo, String descripcion, Date fechaModificacion,
			Set<Modelo> modelos) {
		this.idMarca = idMarca;
		this.pais = pais;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.modelos = modelos;
	}

	@Id

	@Column(name = "id_marca", unique = true, nullable = false)
	public short getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(short idMarca) {
		this.idMarca = idMarca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_vehiculo", nullable = false)
	public TipoVehiculo getTipoVehiculo() {
		return this.tipoVehiculo;
	}

	public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
		this.tipoVehiculo = tipoVehiculo;
	}

	@Column(name = "descripcion", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

}
