package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "car2")
public class Modelo implements java.io.Serializable {

	private long idModelo;
	private Marca marca;
	private String descripcion;
	private Date fechaModificacion;
	private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

	public Modelo() {
	}

	public Modelo(long idModelo, Marca marca, String descripcion, Date fechaModificacion) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
	}

	public Modelo(long idModelo, Marca marca, String descripcion, Date fechaModificacion, Set<Vehiculo> vehiculos) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.vehiculos = vehiculos;
	}

	@Id

	@Column(name = "id_modelo", unique = true, nullable = false)
	public long getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(long idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "descripcion", nullable = false, length = 64)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Vehiculo> getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set<Vehiculo> vehiculos) {
		this.vehiculos = vehiculos;
	}

}
