package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "car2")
public class Pais implements java.io.Serializable {

	private Long idPais;
	private String pais;
	private Date fechaModificacion;
	private Set<Marca> marcas = new HashSet<Marca>(0);
	private Set<Region> regions = new HashSet<Region>(0);

	public Pais() {
	}

	public Pais(String pais, Date fechaModificacion) {
		this.pais = pais;
		this.fechaModificacion = fechaModificacion;
	}

	public Pais(String pais, Date fechaModificacion, Set<Marca> marcas, Set<Region> regions) {
		this.pais = pais;
		this.fechaModificacion = fechaModificacion;
		this.marcas = marcas;
		this.regions = regions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pais", unique = true, nullable = false)
	public Long getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Long idPais) {
		this.idPais = idPais;
	}

	@Column(name = "pais", nullable = false, length = 128)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Marca> getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Set<Marca> marcas) {
		this.marcas = marcas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

	@Override
	public String toString() {
		return "Pais [idPais=" + idPais + ", pais=" + pais + ", fechaModificacion=" + fechaModificacion + "]";
	}
}
