package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", catalog = "car2", uniqueConstraints = @UniqueConstraint(columnNames = "llave"))
public class Parametro implements java.io.Serializable {

	private Long idParametro;
	private String llave;
	private String valor;
	private Date fechaModificacion;

	public Parametro() {
	}

	public Parametro(String llave, String valor, Date fechaModificacion) {
		this.llave = llave;
		this.valor = valor;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_parametro", unique = true, nullable = false)
	public Long getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(Long idParametro) {
		this.idParametro = idParametro;
	}

	@Column(name = "llave", unique = true, nullable = false, length = 64)
	public String getLlave() {
		return this.llave;
	}

	public void setLlave(String llave) {
		this.llave = llave;
	}

	@Column(name = "valor", nullable = false, length = 65535)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
