package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "car2")
public class Proveedor implements java.io.Serializable {

	private Integer idProveedor;
	private String nombre;
	private String direccion;
	private String correo;
	private String telefono;
	private Double latitud;
	private Double longitud;
	private Boolean existenValores;
	private Float valorMinimo;
	private Float valorMaximo;
	private String detalleHtml;
	private Byte calificacion;
	private String url;
	private Date fechaModificacion;
	private Set<RespuestaProveedor> respuestaProveedors = new HashSet<RespuestaProveedor>(0);
	private Set<ProveedorMantencionBase> proveedorMantencionBases = new HashSet<ProveedorMantencionBase>(0);

	public Proveedor() {
	}

	public Proveedor(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Proveedor(String nombre, String direccion, String correo, String telefono, Double latitud, Double longitud,
			Boolean existenValores, Float valorMinimo, Float valorMaximo, String detalleHtml, Byte calificacion,
			String url, Date fechaModificacion, Set<RespuestaProveedor> respuestaProveedors,
			Set<ProveedorMantencionBase> proveedorMantencionBases) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.correo = correo;
		this.telefono = telefono;
		this.latitud = latitud;
		this.longitud = longitud;
		this.existenValores = existenValores;
		this.valorMinimo = valorMinimo;
		this.valorMaximo = valorMaximo;
		this.detalleHtml = detalleHtml;
		this.calificacion = calificacion;
		this.url = url;
		this.fechaModificacion = fechaModificacion;
		this.respuestaProveedors = respuestaProveedors;
		this.proveedorMantencionBases = proveedorMantencionBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_proveedor", unique = true, nullable = false)
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "nombre", length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 512)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "correo", length = 128)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "telefono", length = 128)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "latitud", precision = 22, scale = 0)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 22, scale = 0)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "existen_valores")
	public Boolean getExistenValores() {
		return this.existenValores;
	}

	public void setExistenValores(Boolean existenValores) {
		this.existenValores = existenValores;
	}

	@Column(name = "valor_minimo", precision = 12, scale = 0)
	public Float getValorMinimo() {
		return this.valorMinimo;
	}

	public void setValorMinimo(Float valorMinimo) {
		this.valorMinimo = valorMinimo;
	}

	@Column(name = "valor_maximo", precision = 12, scale = 0)
	public Float getValorMaximo() {
		return this.valorMaximo;
	}

	public void setValorMaximo(Float valorMaximo) {
		this.valorMaximo = valorMaximo;
	}

	@Column(name = "detalle_html", length = 65535)
	public String getDetalleHtml() {
		return this.detalleHtml;
	}

	public void setDetalleHtml(String detalleHtml) {
		this.detalleHtml = detalleHtml;
	}

	@Column(name = "calificacion")
	public Byte getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Byte calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "url", length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<RespuestaProveedor> getRespuestaProveedors() {
		return this.respuestaProveedors;
	}

	public void setRespuestaProveedors(Set<RespuestaProveedor> respuestaProveedors) {
		this.respuestaProveedors = respuestaProveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<ProveedorMantencionBase> getProveedorMantencionBases() {
		return this.proveedorMantencionBases;
	}

	public void setProveedorMantencionBases(Set<ProveedorMantencionBase> proveedorMantencionBases) {
		this.proveedorMantencionBases = proveedorMantencionBases;
	}

}
