package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProvinciaComuna generated by hbm2java
 */
@Entity
@Table(name = "provincia_comuna", catalog = "car2")
public class ProvinciaComuna implements java.io.Serializable {

	private Long idProvinciaComuna;
	private Comuna comuna;
	private Provincia provincia;
	private Date fechaModificacion;

	public ProvinciaComuna() {
	}

	public ProvinciaComuna(Comuna comuna, Provincia provincia, Date fechaModificacion) {
		this.comuna = comuna;
		this.provincia = provincia;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_provincia_comuna", unique = true, nullable = false)
	public Long getIdProvinciaComuna() {
		return this.idProvinciaComuna;
	}

	public void setIdProvinciaComuna(Long idProvinciaComuna) {
		this.idProvinciaComuna = idProvinciaComuna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comuna", nullable = false)
	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provincia", nullable = false)
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
