package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recordatorio generated by hbm2java
 */
@Entity
@Table(name = "recordatorio", catalog = "car2")
public class Recordatorio implements java.io.Serializable {

	private RecordatorioId id;
	private Vehiculo vehiculo;
	private Boolean recordarFecha;
	private Boolean recordarKm;
	private Date fecha;
	private Integer km;
	private String titulo;
	private String descripcion;
	private Date fechaModificacion;
	private boolean borrado;

	public Recordatorio() {
	}

	public Recordatorio(RecordatorioId id, Vehiculo vehiculo, Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.vehiculo = vehiculo;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	public Recordatorio(RecordatorioId id, Vehiculo vehiculo, Boolean recordarFecha, Boolean recordarKm, Date fecha,
			Integer km, String titulo, String descripcion, Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.vehiculo = vehiculo;
		this.recordarFecha = recordarFecha;
		this.recordarKm = recordarKm;
		this.fecha = fecha;
		this.km = km;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRecordatorio", column = @Column(name = "id_recordatorio", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)) })
	public RecordatorioId getId() {
		return this.id;
	}

	public void setId(RecordatorioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_vehiculo", referencedColumnName = "id_vehiculo", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_usuario", referencedColumnName = "id_usuario", nullable = false, insertable = false, updatable = false) })
	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Column(name = "recordar_fecha")
	public Boolean getRecordarFecha() {
		return this.recordarFecha;
	}

	public void setRecordarFecha(Boolean recordarFecha) {
		this.recordarFecha = recordarFecha;
	}

	@Column(name = "recordar_km")
	public Boolean getRecordarKm() {
		return this.recordarKm;
	}

	public void setRecordarKm(Boolean recordarKm) {
		this.recordarKm = recordarKm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "km")
	public Integer getKm() {
		return this.km;
	}

	public void setKm(Integer km) {
		this.km = km;
	}

	@Column(name = "titulo", length = 30)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "borrado", nullable = false)
	public boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

}
