package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RedSocial generated by hbm2java
 */
@Entity
@Table(name = "red_social", catalog = "car2")
public class RedSocial implements java.io.Serializable {

	private long idRedSocial;
	private String redSocial;
	private Date fechaModificacion;
	private Set<Autenticacion> autenticacions = new HashSet<Autenticacion>(0);

	public RedSocial() {
	}

	public RedSocial(long idRedSocial, String redSocial, Date fechaModificacion) {
		this.idRedSocial = idRedSocial;
		this.redSocial = redSocial;
		this.fechaModificacion = fechaModificacion;
	}

	public RedSocial(long idRedSocial, String redSocial, Date fechaModificacion, Set<Autenticacion> autenticacions) {
		this.idRedSocial = idRedSocial;
		this.redSocial = redSocial;
		this.fechaModificacion = fechaModificacion;
		this.autenticacions = autenticacions;
	}

	@Id

	@Column(name = "id_red_social", unique = true, nullable = false)
	public long getIdRedSocial() {
		return this.idRedSocial;
	}

	public void setIdRedSocial(long idRedSocial) {
		this.idRedSocial = idRedSocial;
	}

	@Column(name = "red_social", nullable = false, length = 20)
	public String getRedSocial() {
		return this.redSocial;
	}

	public void setRedSocial(String redSocial) {
		this.redSocial = redSocial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "redSocial")
	public Set<Autenticacion> getAutenticacions() {
		return this.autenticacions;
	}

	public void setAutenticacions(Set<Autenticacion> autenticacions) {
		this.autenticacions = autenticacions;
	}

}
