package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "car2")
public class Region implements java.io.Serializable {

	private Long idRegion;
	private Pais pais;
	private String region;
	private Date fechaModificacion;
	private Set<Comuna> comunas = new HashSet<Comuna>(0);
	private Set<Provincia> provincias = new HashSet<Provincia>(0);

	public Region() {
	}

	public Region(Pais pais, String region, Date fechaModificacion) {
		this.pais = pais;
		this.region = region;
		this.fechaModificacion = fechaModificacion;
	}

	public Region(Pais pais, String region, Date fechaModificacion, Set<Comuna> comunas, Set<Provincia> provincias) {
		this.pais = pais;
		this.region = region;
		this.fechaModificacion = fechaModificacion;
		this.comunas = comunas;
		this.provincias = provincias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_region", unique = true, nullable = false)
	public Long getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Long idRegion) {
		this.idRegion = idRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "region", nullable = false, length = 64)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Comuna> getComunas() {
		return this.comunas;
	}

	public void setComunas(Set<Comuna> comunas) {
		this.comunas = comunas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<Provincia> provincias) {
		this.provincias = provincias;
	}

	@Override
	public String toString() {
		return "Region [idRegion=" + idRegion + ", pais=" + pais + ", region=" + region + ", fechaModificacion="
				+ fechaModificacion + ", comunas=" + comunas + ", provincias=" + provincias + "]";
	}

}
