package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReparacionId generated by hbm2java
 */
@Embeddable
public class ReparacionId implements java.io.Serializable {

	private long idReparacion;
	private long idUsuario;

	public ReparacionId() {
	}

	public ReparacionId(long idReparacion, long idUsuario) {
		this.idReparacion = idReparacion;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_reparacion", nullable = false)
	public long getIdReparacion() {
		return this.idReparacion;
	}

	public void setIdReparacion(long idReparacion) {
		this.idReparacion = idReparacion;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReparacionId))
			return false;
		ReparacionId castOther = (ReparacionId) other;

		return (this.getIdReparacion() == castOther.getIdReparacion())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdReparacion();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
