package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reparacion generated by hbm2java
 */
@Entity
@Table(name = "reparacion", catalog = "car2")
public class Reparacion implements java.io.Serializable {

	private ReparacionId id;
	private Vehiculo vehiculo;
	private String titulo;
	private String descripcion;
	private Integer costo;
	private Date fecha;
	private Date fechaModificacion;
	private boolean borrado;

	public Reparacion() {
	}

	public Reparacion(ReparacionId id, Vehiculo vehiculo, String titulo, String descripcion, Date fechaModificacion,
			boolean borrado) {
		this.id = id;
		this.vehiculo = vehiculo;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	public Reparacion(ReparacionId id, Vehiculo vehiculo, String titulo, String descripcion, Integer costo, Date fecha,
			Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.vehiculo = vehiculo;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.costo = costo;
		this.fecha = fecha;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idReparacion", column = @Column(name = "id_reparacion", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)) })
	public ReparacionId getId() {
		return this.id;
	}

	public void setId(ReparacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_vehiculo", referencedColumnName = "id_vehiculo", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_usuario", referencedColumnName = "id_usuario", nullable = false, insertable = false, updatable = false) })
	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Column(name = "titulo", nullable = false, length = 30)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "costo")
	public Integer getCosto() {
		return this.costo;
	}

	public void setCosto(Integer costo) {
		this.costo = costo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "borrado", nullable = false)
	public boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

}
