package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RestriccionVehicular generated by hbm2java
 */
@Entity
@Table(name = "restriccion_vehicular", catalog = "car2")
public class RestriccionVehicular implements java.io.Serializable {

	private Long idRestriccionVehicular;
	private String digitos;
	private Date fecha;
	private Date fechaModificacion;

	public RestriccionVehicular() {
	}

	public RestriccionVehicular(String digitos, Date fecha, Date fechaModificacion) {
		this.digitos = digitos;
		this.fecha = fecha;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_restriccion_vehicular", unique = true, nullable = false)
	public Long getIdRestriccionVehicular() {
		return this.idRestriccionVehicular;
	}

	public void setIdRestriccionVehicular(Long idRestriccionVehicular) {
		this.idRestriccionVehicular = idRestriccionVehicular;
	}

	@Column(name = "digitos", nullable = false, length = 10)
	public String getDigitos() {
		return this.digitos;
	}

	public void setDigitos(String digitos) {
		this.digitos = digitos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
