package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeguroVehiculo generated by hbm2java
 */
@Entity
@Table(name = "seguro_vehiculo", catalog = "car2")
public class SeguroVehiculo implements java.io.Serializable {

	private SeguroVehiculoId id;
	private CiaSeguros ciaSeguros;
	private TipoSeguro tipoSeguro;
	private Vehiculo vehiculo;
	private String poliza;
	private String observaciones;
	private Date fechaVencimiento;
	private Date fechaModificacion;
	private boolean borrado;

	public SeguroVehiculo() {
	}

	public SeguroVehiculo(SeguroVehiculoId id, CiaSeguros ciaSeguros, TipoSeguro tipoSeguro, Vehiculo vehiculo,
			Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.ciaSeguros = ciaSeguros;
		this.tipoSeguro = tipoSeguro;
		this.vehiculo = vehiculo;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	public SeguroVehiculo(SeguroVehiculoId id, CiaSeguros ciaSeguros, TipoSeguro tipoSeguro, Vehiculo vehiculo,
			String poliza, String observaciones, Date fechaVencimiento, Date fechaModificacion, boolean borrado) {
		this.id = id;
		this.ciaSeguros = ciaSeguros;
		this.tipoSeguro = tipoSeguro;
		this.vehiculo = vehiculo;
		this.poliza = poliza;
		this.observaciones = observaciones;
		this.fechaVencimiento = fechaVencimiento;
		this.fechaModificacion = fechaModificacion;
		this.borrado = borrado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSeguroVehiculo", column = @Column(name = "id_seguro_vehiculo", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)) })
	public SeguroVehiculoId getId() {
		return this.id;
	}

	public void setId(SeguroVehiculoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cia_seguros", nullable = false)
	public CiaSeguros getCiaSeguros() {
		return this.ciaSeguros;
	}

	public void setCiaSeguros(CiaSeguros ciaSeguros) {
		this.ciaSeguros = ciaSeguros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_seguro", nullable = false)
	public TipoSeguro getTipoSeguro() {
		return this.tipoSeguro;
	}

	public void setTipoSeguro(TipoSeguro tipoSeguro) {
		this.tipoSeguro = tipoSeguro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_vehiculo", referencedColumnName = "id_vehiculo", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_usuario", referencedColumnName = "id_usuario", nullable = false, insertable = false, updatable = false) })
	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Column(name = "poliza", length = 65535)
	public String getPoliza() {
		return this.poliza;
	}

	public void setPoliza(String poliza) {
		this.poliza = poliza;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vencimiento", length = 10)
	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "borrado", nullable = false)
	public boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

}
