package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeguroVehiculoId generated by hbm2java
 */
@Embeddable
public class SeguroVehiculoId implements java.io.Serializable {

	private long idSeguroVehiculo;
	private long idUsuario;

	public SeguroVehiculoId() {
	}

	public SeguroVehiculoId(long idSeguroVehiculo, long idUsuario) {
		this.idSeguroVehiculo = idSeguroVehiculo;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_seguro_vehiculo", nullable = false)
	public long getIdSeguroVehiculo() {
		return this.idSeguroVehiculo;
	}

	public void setIdSeguroVehiculo(long idSeguroVehiculo) {
		this.idSeguroVehiculo = idSeguroVehiculo;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeguroVehiculoId))
			return false;
		SeguroVehiculoId castOther = (SeguroVehiculoId) other;

		return (this.getIdSeguroVehiculo() == castOther.getIdSeguroVehiculo())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdSeguroVehiculo();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
