package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoVehiculo generated by hbm2java
 */
@Entity
@Table(name = "tipo_vehiculo", catalog = "car2")
public class TipoVehiculo implements java.io.Serializable {

	private byte idTipoVehiculo;
	private String descripcion;
	private Date fechaModificacion;
	private Set<Marca> marcas = new HashSet<Marca>(0);

	public TipoVehiculo() {
	}

	public TipoVehiculo(byte idTipoVehiculo, String descripcion, Date fechaModificacion) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
	}

	public TipoVehiculo(byte idTipoVehiculo, String descripcion, Date fechaModificacion, Set<Marca> marcas) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.marcas = marcas;
	}

	@Id

	@Column(name = "id_tipo_vehiculo", unique = true, nullable = false)
	public byte getIdTipoVehiculo() {
		return this.idTipoVehiculo;
	}

	public void setIdTipoVehiculo(byte idTipoVehiculo) {
		this.idTipoVehiculo = idTipoVehiculo;
	}

	@Column(name = "descripcion", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVehiculo")
	public Set<Marca> getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Set<Marca> marcas) {
		this.marcas = marcas;
	}

}
