package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoTransmision generated by hbm2java
 */
@Entity
@Table(name = "tipo_transmision", catalog = "car2")
public class TipoTransmision implements java.io.Serializable {

	private byte idTipoTransmision;
	private String descripcion;
	private Date fechaModificacion;
	private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

	public TipoTransmision() {
	}

	public TipoTransmision(byte idTipoTransmision, String descripcion, Date fechaModificacion) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
	}

	public TipoTransmision(byte idTipoTransmision, String descripcion, Date fechaModificacion,
			Set<Vehiculo> vehiculos) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
		this.fechaModificacion = fechaModificacion;
		this.vehiculos = vehiculos;
	}

	@Id

	@Column(name = "id_tipo_transmision", unique = true, nullable = false)
	public byte getIdTipoTransmision() {
		return this.idTipoTransmision;
	}

	public void setIdTipoTransmision(byte idTipoTransmision) {
		this.idTipoTransmision = idTipoTransmision;
	}

	@Column(name = "descripcion", nullable = false, length = 16)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTransmision")
	public Set<Vehiculo> getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set<Vehiculo> vehiculos) {
		this.vehiculos = vehiculos;
	}

}
