package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioInfo generated by hbm2java
 */
@Entity
@Table(name = "usuario_info", catalog = "car2")
public class UsuarioInfo implements java.io.Serializable {

	private Long idUsuarioInfo;
	private Usuario usuario;
	private Double latitud;
	private Double longitud;
	private String houseNumber;
	private String road;
	private String neighbourhood;
	private String suburb;
	private String city;
	private String county;
	private String state;
	private String country;
	private String countryCode;
	private String android;
	private String appVersion;

	public UsuarioInfo() {
	}

	public UsuarioInfo(Usuario usuario) {
		this.usuario = usuario;
	}

	public UsuarioInfo(Usuario usuario, Double latitud, Double longitud, String houseNumber, String road,
			String neighbourhood, String suburb, String city, String county, String state, String country,
			String countryCode, String android, String appVersion) {
		this.usuario = usuario;
		this.latitud = latitud;
		this.longitud = longitud;
		this.houseNumber = houseNumber;
		this.road = road;
		this.neighbourhood = neighbourhood;
		this.suburb = suburb;
		this.city = city;
		this.county = county;
		this.state = state;
		this.country = country;
		this.countryCode = countryCode;
		this.android = android;
		this.appVersion = appVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario_info", unique = true, nullable = false)
	public Long getIdUsuarioInfo() {
		return this.idUsuarioInfo;
	}

	public void setIdUsuarioInfo(Long idUsuarioInfo) {
		this.idUsuarioInfo = idUsuarioInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "latitud", precision = 22, scale = 0)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 22, scale = 0)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "house_number", length = 16)
	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	@Column(name = "road", length = 256)
	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	@Column(name = "neighbourhood", length = 256)
	public String getNeighbourhood() {
		return this.neighbourhood;
	}

	public void setNeighbourhood(String neighbourhood) {
		this.neighbourhood = neighbourhood;
	}

	@Column(name = "suburb", length = 256)
	public String getSuburb() {
		return this.suburb;
	}

	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	@Column(name = "city", length = 256)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", length = 256)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "state", length = 256)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 256)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "country_code", length = 8)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "android", length = 16)
	public String getAndroid() {
		return this.android;
	}

	public void setAndroid(String android) {
		this.android = android;
	}

	@Column(name = "app_version", length = 16)
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

}
