package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioWeb generated by hbm2java
 */
@Entity
@Table(name = "usuario_web", catalog = "car2", uniqueConstraints = { @UniqueConstraint(columnNames = "nombre_usuario"),
		@UniqueConstraint(columnNames = "email") })
public class UsuarioWeb implements java.io.Serializable {

	private Integer idUsuarioWeb;
	private String nombreUsuario;
	private String contrasena;
	private String nombre;
	private String apellidos;
	private String email;
	private boolean activo;
	private boolean borrado;

	public UsuarioWeb() {
	}

	public UsuarioWeb(String nombreUsuario, String contrasena, String nombre, String apellidos, String email,
			boolean activo, boolean borrado) {
		this.nombreUsuario = nombreUsuario;
		this.contrasena = contrasena;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.activo = activo;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario_web", unique = true, nullable = false)
	public Integer getIdUsuarioWeb() {
		return this.idUsuarioWeb;
	}

	public void setIdUsuarioWeb(Integer idUsuarioWeb) {
		this.idUsuarioWeb = idUsuarioWeb;
	}

	@Column(name = "nombre_usuario", unique = true, nullable = false, length = 16)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@Column(name = "contrasena", nullable = false, length = 32)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "nombre", nullable = false, length = 16)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", nullable = false, length = 32)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "email", unique = true, nullable = false, length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "borrado", nullable = false)
	public boolean isBorrado() {
		return this.borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

}
