package cl.dsoft.car.data.entities;
// Generated 17-05-2020 20:45:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwCampaniaUsuarioId generated by hbm2java
 */
@Embeddable
public class VwCampaniaUsuarioId implements java.io.Serializable {

	private long id;
	private long idUsuario;
	private Date fechaInicio;
	private Date fechaFin;
	private Short periodicidad;
	private Short numeroImpresiones;
	private String detalle;
	private Date fechaModificacion;

	public VwCampaniaUsuarioId() {
	}

	public VwCampaniaUsuarioId(long id, long idUsuario, String detalle, Date fechaModificacion) {
		this.id = id;
		this.idUsuario = idUsuario;
		this.detalle = detalle;
		this.fechaModificacion = fechaModificacion;
	}

	public VwCampaniaUsuarioId(long id, long idUsuario, Date fechaInicio, Date fechaFin, Short periodicidad,
			Short numeroImpresiones, String detalle, Date fechaModificacion) {
		this.id = id;
		this.idUsuario = idUsuario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.periodicidad = periodicidad;
		this.numeroImpresiones = numeroImpresiones;
		this.detalle = detalle;
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "fecha_inicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "fecha_fin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "periodicidad")
	public Short getPeriodicidad() {
		return this.periodicidad;
	}

	public void setPeriodicidad(Short periodicidad) {
		this.periodicidad = periodicidad;
	}

	@Column(name = "numero_impresiones")
	public Short getNumeroImpresiones() {
		return this.numeroImpresiones;
	}

	public void setNumeroImpresiones(Short numeroImpresiones) {
		this.numeroImpresiones = numeroImpresiones;
	}

	@Column(name = "detalle", nullable = false, length = 65535)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwCampaniaUsuarioId))
			return false;
		VwCampaniaUsuarioId castOther = (VwCampaniaUsuarioId) other;

		return (this.getId() == castOther.getId()) && (this.getIdUsuario() == castOther.getIdUsuario())
				&& ((this.getFechaInicio() == castOther.getFechaInicio())
						|| (this.getFechaInicio() != null && castOther.getFechaInicio() != null
								&& this.getFechaInicio().equals(castOther.getFechaInicio())))
				&& ((this.getFechaFin() == castOther.getFechaFin()) || (this.getFechaFin() != null
						&& castOther.getFechaFin() != null && this.getFechaFin().equals(castOther.getFechaFin())))
				&& ((this.getPeriodicidad() == castOther.getPeriodicidad())
						|| (this.getPeriodicidad() != null && castOther.getPeriodicidad() != null
								&& this.getPeriodicidad().equals(castOther.getPeriodicidad())))
				&& ((this.getNumeroImpresiones() == castOther.getNumeroImpresiones())
						|| (this.getNumeroImpresiones() != null && castOther.getNumeroImpresiones() != null
								&& this.getNumeroImpresiones().equals(castOther.getNumeroImpresiones())))
				&& ((this.getDetalle() == castOther.getDetalle()) || (this.getDetalle() != null
						&& castOther.getDetalle() != null && this.getDetalle().equals(castOther.getDetalle())))
				&& ((this.getFechaModificacion() == castOther.getFechaModificacion())
						|| (this.getFechaModificacion() != null && castOther.getFechaModificacion() != null
								&& this.getFechaModificacion().equals(castOther.getFechaModificacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getIdUsuario();
		result = 37 * result + (getFechaInicio() == null ? 0 : this.getFechaInicio().hashCode());
		result = 37 * result + (getFechaFin() == null ? 0 : this.getFechaFin().hashCode());
		result = 37 * result + (getPeriodicidad() == null ? 0 : this.getPeriodicidad().hashCode());
		result = 37 * result + (getNumeroImpresiones() == null ? 0 : this.getNumeroImpresiones().hashCode());
		result = 37 * result + (getDetalle() == null ? 0 : this.getDetalle().hashCode());
		result = 37 * result + (getFechaModificacion() == null ? 0 : this.getFechaModificacion().hashCode());
		return result;
	}

}
